// Code generated by ent-elastic, DO NOT EDIT.
package test

import (
	"github.com/guihouchang/go-elasticsearch/test/migrate"
	"github.com/olivere/elastic"
)

type Client struct {
	client *elastic.Client
	Schema *migrate.Schema
}

func NewClient(client *elastic.Client) *Client {
	return &Client{
		client: client,
		Schema: migrate.NewSchema(client),
	}
}
