// Code generated by ent-elastic, DO NOT EDIT.
package userdata

const (
	Label = "user_data"

	FieldID = "id"

	FieldKeywordKkkk = "keyword_kkkk"

	FieldByteBbbb = "byte_bbbb"

	FieldShortSsss = "short_ssss"

	FieldIntIiii = "int_iiii"

	FieldLongLlll = "long_llll"

	FieldFloatFfff = "float_ffff"

	FieldDoubleDdddd = "double_ddddd"

	FieldBoolBbbb = "bool_bbbb"

	FieldDateDddd = "date_dddd"
)
