// Code generated by ent-elastic, DO NOT EDIT.

package migrate

import (
	"context"
	"fmt"
	"github.com/google/go-cmp/cmp"
	"github.com/guihouchang/go-elasticsearch/schema/field"
	"github.com/olivere/elastic/v7"
)

var (
	UserDataMapping = &field.Mapping{
		Name: "user_data",
		Properties: map[string]interface{}{

			"id": map[string]interface{}{
				"type":     "text",
				"analyzer": "ik_max_word",
			},

			"keyword_kkkk": map[string]interface{}{
				"type": "keyword",
			},

			"byte_bbbb": map[string]interface{}{
				"type": "byte",
			},

			"short_ssss": map[string]interface{}{
				"type": "short",
			},

			"int_iiii": map[string]interface{}{
				"type": "integer",
			},

			"long_llll": map[string]interface{}{
				"type": "long",
			},

			"float_ffff": map[string]interface{}{
				"type": "float",
			},

			"double_ddddd": map[string]interface{}{
				"type": "double",
			},

			"bool_bbbb": map[string]interface{}{
				"type": "boolean",
			},

			"date_dddd": map[string]interface{}{
				"type":   "date",
				"format": "yyyy-MM-dd HH:mm:ss",
			},
		},

		Settings: map[string]interface{}{

			"number_of_replicas": 2,

			"number_of_shards": 1,
		},
	}

	Tables = []*field.Mapping{
		UserDataMapping,
	}
)

type Schema struct {
	client *elastic.Client
}

func NewSchema(client *elastic.Client) *Schema {
	return &Schema{client: client}
}

func (s *Schema) Create(ctx context.Context) error {
	return Create(ctx, s, Tables)
}

func getProperties(mapping map[string]interface{}, name string) (map[string]interface{}, error) {
	if mappingData, ok := mapping[name]; ok {
		if tmpData, ok := mappingData.(map[string]interface{}); ok {
			if tmpData, ok := tmpData["mappings"]; ok {
				if tmpData, ok := tmpData.(map[string]interface{}); ok {
					if tmpData, ok := tmpData["properties"]; ok {
						if properties, ok := tmpData.(map[string]interface{}); ok {
							return properties, nil
						}
					}
				}
			}
		}
	}

	return nil, fmt.Errorf("properties not found")
}

func Create(ctx context.Context, s *Schema, mappings []*field.Mapping) error {
	for _, m := range mappings {
		exist, err := s.client.IndexExists(m.Name).Do(ctx)
		if err != nil {
			return err
		}

		if !exist {
			_, err := s.client.CreateIndex(m.Name).BodyJson(m.CreateBody()).Do(ctx)
			if err != nil {
				return err
			}
		} else {
			// 获取当前的mapping
			mapping, err := s.client.GetMapping().Index(m.Name).Do(ctx)
			if err != nil {
				return err
			}

			properties, err := getProperties(mapping, m.Name)
			if err != nil {
				return err
			}

			// 比较mapping是否有变更
			if cmp.Equal(properties, m.Properties) {
				continue
			}

			// 先进行备份
			_, err = s.client.Reindex().Body(m.BackupBody()).Do(ctx)
			if err != nil {
				return err
			}

			// 删除旧索引
			_, err = s.client.DeleteIndex(m.Name).Do(ctx)
			if err != nil {
				return err
			}

			// 创建索引
			_, err = s.client.CreateIndex(m.Name).BodyJson(m.CreateBody()).Do(ctx)
			if err != nil {
				return err
			}

			exist, err := s.client.IndexExists(m.BackupName()).Do(ctx)
			if err != nil {
				return err
			}

			if exist {
				// 恢复数据
				_, err = s.client.Reindex().Body(m.RecoveryBody()).Do(ctx)
				// 删除旧索引
				_, err = s.client.DeleteIndex(m.BackupName()).Do(ctx)
				if err != nil {
					return err
				}
			}

			return err
		}
	}
	return nil
}
